# Generated by Django 5.2.12 on 2026-03-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="emoji",
            field=models.CharField(blank=True, max_length=10, verbose_name="Emoji"),
        ),
        migrations.AddField(
            model_name="user",
            name="organisation",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Organisation"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("pm", "Project Manager"),
                    ("developer", "Developer"),
                    ("observer", "Observer"),
                ],
                default="developer",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
