# Generated by Django 5.2.13 on 2026-04-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_emoji_user_organisation_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="emoji",
        ),
    ]
