#!/bin/bash
# Interactively create a production .env file from .env.template.
# Run once after cloning the repository.
# Do NOT run as root — secrets are written to .env owned by the current user.

set -euo pipefail

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'
info()  { echo -e "${GREEN}[configure]${NC} $*"; }
warn()  { echo -e "${YELLOW}[configure]${NC} $*"; }
prompt(){ echo -e "${BOLD}$*${NC}"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$REPO_DIR"

if [[ ! -f .env.template ]]; then
    echo "ERROR: .env.template not found. Are you in the repository root?"
    exit 1
fi

if [[ -f .env ]]; then
    warn ".env already exists."
    read -rp "Overwrite it? This will replace all current secrets. [y/N] " confirm
    [[ "$confirm" =~ ^[Yy]$ ]] || { info "Aborted. Existing .env unchanged."; exit 0; }
fi

echo
info "This script will generate a production .env with fresh secrets."
info "You will be prompted for settings that cannot be auto-generated."
echo

# ---------------------------------------------------------------------------
# Collect user inputs
# ---------------------------------------------------------------------------
prompt "Domain name (e.g. myapp.adacs-gpoole.cloud.edu.au):"
read -rp "  DOMAIN_NAME: " DOMAIN_NAME
[[ -n "$DOMAIN_NAME" ]] || { echo "ERROR: domain name is required."; exit 1; }

prompt "Admin email address (used to register the Let's Encrypt certificate):"
read -rp "  ADMIN_EMAIL: " ADMIN_EMAIL
[[ -n "$ADMIN_EMAIL" ]] || { echo "ERROR: admin email is required."; exit 1; }

prompt "Timezone (default: Australia/Melbourne):"
read -rp "  DJANGO_TIMEZONE [Australia/Melbourne]: " TIMEZONE
TIMEZONE="${TIMEZONE:-Australia/Melbourne}"

echo
info "Email / SMTP configuration"
info "  Leave EMAIL_HOST blank to keep Mailpit (email won't be delivered externally)."
prompt "SMTP host (blank = keep Mailpit for local capture only):"
read -rp "  EMAIL_HOST: " EMAIL_HOST
EMAIL_HOST="${EMAIL_HOST:-mailpit}"

if [[ "$EMAIL_HOST" == "mailpit" ]]; then
    EMAIL_PORT="1025"
    EMAIL_HOST_USER=""
    EMAIL_HOST_PASSWORD=""
    EMAIL_USE_TLS="False"
    EMAIL_USE_SSL="False"
    warn "Using Mailpit — emails will be captured locally, not delivered to recipients."
else
    prompt "SMTP port (commonly 587 for STARTTLS, 465 for SSL):"
    read -rp "  EMAIL_PORT [587]: " EMAIL_PORT
    EMAIL_PORT="${EMAIL_PORT:-587}"

    prompt "SMTP username (leave blank if not required):"
    read -rp "  EMAIL_HOST_USER: " EMAIL_HOST_USER

    if [[ -n "$EMAIL_HOST_USER" ]]; then
        prompt "SMTP password:"
        read -rsp "  EMAIL_HOST_PASSWORD: " EMAIL_HOST_PASSWORD
        echo
    else
        EMAIL_HOST_PASSWORD=""
    fi

    # Port 465 uses implicit TLS (SSL); everything else (e.g. 587) uses STARTTLS.
    # These are mutually exclusive — Django rejects both being enabled at once.
    if [[ "$EMAIL_PORT" == "465" ]]; then
        EMAIL_USE_TLS="False"
        EMAIL_USE_SSL="True"
    else
        EMAIL_USE_TLS="True"
        EMAIL_USE_SSL="False"
    fi
fi

echo
info "Google reCAPTCHA keys (required in production)."
info "  Register at: https://www.google.com/recaptcha/admin — use v2 Checkbox."
prompt "reCAPTCHA site key:"
read -rp "  RECAPTCHA_PUBLIC_KEY: " RECAPTCHA_PUBLIC_KEY
prompt "reCAPTCHA secret key:"
read -rsp "  RECAPTCHA_PRIVATE_KEY: " RECAPTCHA_PRIVATE_KEY
echo

echo
info "Nectar Object Storage backup (optional)."
info "  Uploads each dump to Swift so backups survive VM loss."
info "  Requires the OpenStack CLI and sourced credentials (. ~/openrc.sh) at backup time."
info "  Leave blank to skip — you can add SWIFT_BACKUP_CONTAINER to .env later."
prompt "Swift container name for backups (blank = disabled):"
read -rp "  SWIFT_BACKUP_CONTAINER: " SWIFT_BACKUP_CONTAINER

SWIFT_RETENTION_DAYS=""
if [[ -n "$SWIFT_BACKUP_CONTAINER" ]]; then
    prompt "Retention period for Swift backup objects in days (default: 90):"
    read -rp "  SWIFT_RETENTION_DAYS [90]: " SWIFT_RETENTION_DAYS
    SWIFT_RETENTION_DAYS="${SWIFT_RETENTION_DAYS:-90}"
fi

# ---------------------------------------------------------------------------
# Auto-generate secrets (no Django dependency required)
# ---------------------------------------------------------------------------
info "Generating secrets..."
SECRET_KEY=$(python3 -c 'import secrets, string; \
    chars = string.ascii_letters + string.digits + "!@#%^&*(-_=+)"; \
    print("".join(secrets.choice(chars) for _ in range(50)))')
MYSQL_ROOT_PASSWORD=$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')
MYSQL_PASSWORD=$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')

# ---------------------------------------------------------------------------
# Write .env
# ---------------------------------------------------------------------------
cat > .env << EOF
# Security Warning! Do not commit this file to any VCS!
# Generated by scripts/configure.sh on $(date -u '+%Y-%m-%d %H:%M UTC')

# === General ===
DOMAIN_NAME=${DOMAIN_NAME}

# === Admin ===
ADMIN_EMAIL=${ADMIN_EMAIL}

# === Django ===
DJANGO_SECRET_KEY=${SECRET_KEY}
DJANGO_DEBUG=False
DJANGO_TIMEZONE=${TIMEZONE}

# === Database ===
# These variables are consumed by both Django and the MySQL Docker image.
# See: https://hub.docker.com/_/mysql
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_DATABASE=adacs_team_management
MYSQL_USER=adacs_team_management
MYSQL_PASSWORD=${MYSQL_PASSWORD}

# Production settings use service name "db" (set in prod.py).
# Listed here for completeness.
DJANGO_MYSQL_HOST=db
DJANGO_MYSQL_PORT=3306

# === Email ===
EMAIL_HOST=${EMAIL_HOST}
EMAIL_PORT=${EMAIL_PORT}
EOF

# Append SMTP credentials only if a real server is configured
if [[ "$EMAIL_HOST" != "mailpit" ]]; then
    cat >> .env << EOF
EMAIL_HOST_USER=${EMAIL_HOST_USER}
EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
EMAIL_USE_TLS=${EMAIL_USE_TLS}
EMAIL_USE_SSL=${EMAIL_USE_SSL}
EOF
fi

cat >> .env << EOF

# === Backups ===
# Set SWIFT_BACKUP_CONTAINER to push each dump to Nectar Object Storage (Swift).
# Create the container first: openstack container create <name>
# Credentials must be sourced at backup time: . ~/openrc.sh
SWIFT_BACKUP_CONTAINER=${SWIFT_BACKUP_CONTAINER}
SWIFT_RETENTION_DAYS=${SWIFT_RETENTION_DAYS:-90}
EOF

cat >> .env << EOF

# === HTTPS hardening (must be True for production) ===
SESSION_COOKIE_SECURE=True
CSRF_COOKIE_SECURE=True
SECURE_SSL_REDIRECT=True

# === reCAPTCHA ===
RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
EOF

chmod 600 .env
info ".env created with permissions 600."

# ---------------------------------------------------------------------------
# Sanity check — ensure no placeholder values remain
# ---------------------------------------------------------------------------
if grep -q '__CHANGEME__' .env; then
    warn "WARNING: .env still contains __CHANGEME__ placeholders."
    warn "Edit .env manually before running scripts/deploy.sh."
else
    info "No placeholder values detected."
fi

echo
info "Summary (secrets are masked):"
echo "  DOMAIN_NAME         = ${DOMAIN_NAME}"
echo "  ADMIN_EMAIL         = ${ADMIN_EMAIL}"
echo "  DJANGO_TIMEZONE     = ${TIMEZONE}"
echo "  EMAIL_HOST          = ${EMAIL_HOST}:${EMAIL_PORT}"
echo "  DJANGO_SECRET_KEY   = ${SECRET_KEY:0:6}... (auto-generated, 50 chars)"
echo "  MYSQL_ROOT_PASSWORD = *** (auto-generated)"
echo "  MYSQL_PASSWORD      = *** (auto-generated)"
echo "  RECAPTCHA_PUBLIC_KEY= ${RECAPTCHA_PUBLIC_KEY:0:6}..."
if [[ -n "$SWIFT_BACKUP_CONTAINER" ]]; then
    echo "  SWIFT_BACKUP_CONTAINER = ${SWIFT_BACKUP_CONTAINER}"
    echo "  SWIFT_RETENTION_DAYS   = ${SWIFT_RETENTION_DAYS}"
    echo ""
    warn "Remember to create the Swift container before running backups:"
    warn "  . ~/openrc.sh && openstack container create ${SWIFT_BACKUP_CONTAINER}"
fi
echo
info "Next: bash scripts/setup-dns.sh --zone <zone> --ip <ip>"
