# Generated by Django 5.2.12 on 2026-03-23 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("#4E79A7", "Steel Blue"),
                            ("#F28E2B", "Orange"),
                            ("#E15759", "Brick Red"),
                            ("#76B7B2", "Teal"),
                            ("#59A14F", "Green"),
                            ("#EDC948", "Yellow"),
                            ("#B07AA1", "Purple"),
                            ("#FF9DA7", "Pink"),
                            ("#9C755F", "Brown"),
                            ("#BAB0AC", "Grey"),
                        ],
                        max_length=7,
                        verbose_name="colour",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeveloperProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("#4E79A7", "Steel Blue"),
                            ("#F28E2B", "Orange"),
                            ("#E15759", "Brick Red"),
                            ("#76B7B2", "Teal"),
                            ("#59A14F", "Green"),
                            ("#EDC948", "Yellow"),
                            ("#B07AA1", "Purple"),
                            ("#FF9DA7", "Pink"),
                            ("#9C755F", "Brown"),
                            ("#BAB0AC", "Grey"),
                        ],
                        max_length=7,
                        verbose_name="colour",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "developer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="developers", to="planning.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Developer Profile",
                "verbose_name_plural": "Developer Profiles",
            },
        ),
        migrations.CreateModel(
            name="ObserverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "observer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_access",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Projects this observer can view. Leave empty for no access.",
                        related_name="observer_access",
                        to="planning.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observer Profile",
                "verbose_name_plural": "Observer Profiles",
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="year")),
                (
                    "semester_type",
                    models.CharField(
                        choices=[("A", "A (Jan–Jun)"), ("B", "B (Jul–Dec)")],
                        max_length=1,
                        verbose_name="semester",
                    ),
                ),
            ],
            options={
                "ordering": ["year", "semester_type"],
                "unique_together": {("year", "semester_type")},
            },
        ),
        migrations.AddField(
            model_name="project",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="planning.stream",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="planning.tag"
            ),
        ),
        migrations.CreateModel(
            name="ProjectSemesterName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_names",
                        to="planning.project",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_names",
                        to="planning.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["semester__year", "semester__semester_type"],
                "unique_together": {("project", "semester")},
            },
        ),
        migrations.CreateModel(
            name="ProjectAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed (specified semesters)"),
                            ("indefinite", "Indefinite (ongoing)"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="allocation type",
                    ),
                ),
                (
                    "weeks_new",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="new weeks allocated",
                    ),
                ),
                (
                    "weeks_carryover",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="weeks carried over",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="planning.project",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_allocations",
                        to="planning.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["semester__year", "semester__semester_type"],
                "unique_together": {("project", "semester")},
            },
        ),
        migrations.CreateModel(
            name="SemesterDeveloper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effort_available",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="effort available (weeks)",
                    ),
                ),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_records",
                        to="planning.developerprofile",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_records",
                        to="planning.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["semester__year", "semester__semester_type"],
                "unique_together": {("developer", "semester")},
            },
        ),
    ]
