# Generated by Django 5.2.12 on 2026-03-23 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('A', 'A (Jan-Jun)'), ('B', 'B (Jul-Dec)')], max_length=1, verbose_name='semester'),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_periods', to='planning.developerprofile')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('effort_multiplier', models.FloatField(default=1.0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='planning.developerprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='planning.project')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='planning.semester')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
