# Generated by Django 5.2.12 on 2026-04-02 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_alter_semester_semester_type_leave_phase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semesterdeveloper",
            name="effort_available",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="effort available (weeks)",
            ),
        ),
    ]
