# Generated by Django 5.2.12 on 2026-04-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_add_effort_available_min_validator"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperLane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lanes",
                        to="planning.developerprofile",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lanes",
                        to="planning.semester",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
                "unique_together": {("developer", "semester", "order")},
            },
        ),
        migrations.AddField(
            model_name="phase",
            name="lane",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="phases",
                to="planning.developerlane",
            ),
        ),
    ]
