# Generated by Django 5.2.12 on 2026-04-04 09:04

from collections import defaultdict

from django.db import migrations


def assign_phases_to_lanes(apps, schema_editor):
    Phase = apps.get_model("planning", "Phase")
    DeveloperLane = apps.get_model("planning", "DeveloperLane")

    groups = defaultdict(list)
    for phase in Phase.objects.all():
        groups[(phase.developer_id, phase.semester_id)].append(phase)

    for (developer_id, semester_id), phase_list in groups.items():
        lane, _ = DeveloperLane.objects.get_or_create(
            developer_id=developer_id,
            semester_id=semester_id,
            defaults={"order": 0},
        )
        for phase in phase_list:
            phase.lane = lane
            phase.save(update_fields=["lane_id"])


def reverse_assign(apps, schema_editor):
    Phase = apps.get_model("planning", "Phase")
    Phase.objects.all().update(lane=None)


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0004_add_developer_lane"),
    ]

    operations = [
        migrations.RunPython(assign_phases_to_lanes, reverse_assign),
    ]
