# Generated by Django 5.2.12 on 2026-04-07 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0005_migrate_phases_to_lanes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phase",
            name="effort_multiplier",
            field=models.FloatField(
                default=1.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="phase",
            index=models.Index(
                fields=["developer", "semester"], name="planning_ph_develop_ba7abe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phase",
            index=models.Index(
                fields=["start_date", "end_date"], name="planning_ph_start_d_56840a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phase",
            index=models.Index(
                fields=["lane", "start_date", "end_date"],
                name="planning_ph_lane_id_7c4e2b_idx",
            ),
        ),
    ]
