# Generated by Django 5.2.13 on 2026-04-10 00:18

from django.db import migrations, models

_PALETTE = [
    "#4E79A7", "#F28E2B", "#E15759", "#76B7B2", "#59A14F",
    "#EDC948", "#B07AA1", "#FF9DA7", "#9C755F", "#BAB0AC",
]


def _backfill_colours(apps, schema_editor):
    Tag = apps.get_model("planning", "Tag")
    Stream = apps.get_model("planning", "Stream")
    for i, obj in enumerate(Tag.objects.all()):
        obj.colour = _PALETTE[i % len(_PALETTE)]
        obj.save()
    for i, obj in enumerate(Stream.objects.all()):
        obj.colour = _PALETTE[i % len(_PALETTE)]
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0008_remove_project_stream_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="colour",
            field=models.CharField(
                blank=True,
                choices=[
                    ("#4E79A7", "Steel Blue"),
                    ("#F28E2B", "Orange"),
                    ("#E15759", "Brick Red"),
                    ("#76B7B2", "Teal"),
                    ("#59A14F", "Green"),
                    ("#EDC948", "Yellow"),
                    ("#B07AA1", "Purple"),
                    ("#FF9DA7", "Pink"),
                    ("#9C755F", "Brown"),
                    ("#BAB0AC", "Grey"),
                ],
                max_length=7,
                verbose_name="colour",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="colour",
            field=models.CharField(
                blank=True,
                choices=[
                    ("#4E79A7", "Steel Blue"),
                    ("#F28E2B", "Orange"),
                    ("#E15759", "Brick Red"),
                    ("#76B7B2", "Teal"),
                    ("#59A14F", "Green"),
                    ("#EDC948", "Yellow"),
                    ("#B07AA1", "Purple"),
                    ("#FF9DA7", "Pink"),
                    ("#9C755F", "Brown"),
                    ("#BAB0AC", "Grey"),
                ],
                max_length=7,
                verbose_name="colour",
            ),
        ),
        migrations.RunPython(_backfill_colours, migrations.RunPython.noop),
    ]
