# Generated by Django 5.2.13 on 2026-04-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0009_tag_stream_add_colour"),
    ]

    operations = [
        migrations.AddField(
            model_name="observerprofile",
            name="stream_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Streams this observer can view. All projects in these streams are accessible.",
                related_name="observer_access",
                to="planning.stream",
            ),
        ),
    ]
