# Generated by Django 5.2.13 on 2026-04-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0013_alter_developerprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="developerprofile",
            name="base_effort_weeks",
            field=models.DecimalField(
                decimal_places=2,
                default=20,
                max_digits=6,
                verbose_name="base effort (weeks/semester)",
            ),
        ),
    ]
