# Generated by Django 5.2.13 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0014_add_base_effort_weeks"),
    ]

    operations = [
        migrations.AddField(
            model_name="semesterdeveloper",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="semester_developer_records", to="planning.tag"
            ),
        ),
    ]
