# Generated by Django 5.2.13 on 2026-04-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0016_project_leads_continuation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectallocation",
            name="allocation_type",
        ),
        migrations.DeleteModel(
            name="ObserverProfile",
        ),
    ]
