# Generated by Django 5.2.13 on 2026-04-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0018_user_project_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprojectaccess",
            name="all_project_access",
            field=models.BooleanField(
                default=False,
                help_text="When true, user can view all projects regardless of project_access list.",
            ),
        ),
        migrations.AddField(
            model_name="userprojectaccess",
            name="all_stream_access",
            field=models.BooleanField(
                default=False,
                help_text="When true, user can view all projects in all streams.",
            ),
        ),
    ]
