# Generated by Django 5.2.13 on 2026-04-27 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0019_userprojectaccess_all_project_access_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsemestername",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[^|]*$", "Name may not contain '|'."
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="stream",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[^|]*$", "Name may not contain '|'."
                    )
                ],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[^|]*$", "Name may not contain '|'."
                    )
                ],
                verbose_name="name",
            ),
        ),
    ]
