# Generated by Django 5.2.13 on 2026-04-27 08:06

import apps.planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0020_alter_projectsemestername_name_alter_stream_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsemestername",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[apps.planning.models._validate_name_chars],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="stream",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[apps.planning.models._validate_name_chars],
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[apps.planning.models._validate_name_chars],
                verbose_name="name",
            ),
        ),
    ]
