# Generated by Django 5.2.13 on 2026-05-04 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0021_alter_projectsemestername_name_alter_stream_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="continuation_of_semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="planning.semester",
            ),
        ),
    ]
