# Generated by Django 5.2.13 on 2026-05-05 10:15

import apps.planning.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0023_remove_projectsemestername_add_project_name_semester"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[apps.planning.models._validate_name_chars],
                verbose_name="name",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("continuation_of__isnull", False)),
                fields=("continuation_of",),
                name="project_continuation_of_unique",
            ),
        ),
    ]
