# Generated by Django 5.2.13 on 2026-07-09 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0028_fold_weeks_carryover_into_weeks_new"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectallocation",
            name="weeks_carryover",
        ),
        migrations.CreateModel(
            name="ProjectTimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weeks",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=6, verbose_name="weeks"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="comment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="planning.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project time entry",
                "verbose_name_plural": "Project time entries",
                "ordering": ["id"],
            },
        ),
    ]
