# Generated by Django 5.2.13 on 2026-07-09 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0029_remove_projectallocation_weeks_carryover_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprojectaccess",
            name="developer_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_access_policy",
                to="planning.developerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="userprojectaccess",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_access_policy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="userprojectaccess",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("developer_profile__isnull", True), ("user__isnull", False)
                    ),
                    models.Q(
                        ("developer_profile__isnull", False), ("user__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="userprojectaccess_exactly_one_owner",
            ),
        ),
    ]
